version: '2'
services:
  gmaps-frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - gmaps-backend
  gmaps-backend:
    build: ./backend
    ports:
      - '8080:8080'
    depends_on:
      - gmaps-mongo
  gmaps-mongo:
    image: mongo
    ports:
      - '27017:27017'
